### Crear un nuevo libro (POST)
POST http://localhost:5000/libros
Content-Type: application/json

{
  "titulo": "Cien Años de Soledad",
  "autor": "Gabriel García Márquez",
  "anio_publicacion": 1967,
  "bibliotecario_id": 1
}
